// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asuhgzeoxzebeynxoleq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzdWhnemVveHplYmV5bnhvbGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NDk2MzQsImV4cCI6MjA1NzUyNTYzNH0.pzqaZE7LAvNbsmBXCGGziDQe3jy6i6rNGnCuuqdc_jI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);